---

- name: Create PostgreSQL user and database for Weather API
  hosts: master
  become: true
  become_method: sudo
  gather_facts: true
  tags: always
  any_errors_fatal: true
  vars_files:
    - vars/main.yml
  environment: "{{ proxy_env | default({}) }}"

  roles:
    - role: initdb
